export const BRANDS = [
  "colourpop",
  "boosh",
  "deciem",
  "zorah biocosmetiques",
  "w3llpeople",
  "sally b's skin yummies",
  "rejuva minerals",
  "nudus",
  "penny lane organics",
  "marienatie",
  "maia's mineral galaxy",
  "lotus cosmetics usa",
  "green people",
  "c'est moi",
  "coastal classic creation",
  "glossier",
  "alva",
  "nyx",
];
